### ISSUE TITLE
New currency don't work

### ISSUE THREAD

**Issue by eson57** [ckazzku/zatraty#1]
I tried to add SEK (Swedish krona) with no success.

**Comment by ckazzku** [comment]
There is a unicode symbol for this currency?

**Comment by eson57** [comment]
No, just SEK.

`<entry code="SEK" unicode-decimal="107, 114" unicode-hex="6b, 72">Sweden Krona</entry>`

I guess you already know about this...
https://gist.github.com/bzerangue/5484121

**Comment by ckazzku** [comment]
> unicode-hex="6b, 72"

it's just a "kr"...
http://www.wazu.jp/gallery/Test_CurrencySymbols.html

**Comment by eson57** [comment]
Well, I guess that would be okay to. "kr" is short for krona, but the actual international code is SEK.

**Comment by eson57** [comment]
Thanks! :+1:
