### ISSUE TITLE
Rounding bug and deletion bug

### ISSUE THREAD

**Issue by KingDuckZ** [ckazzku/zatraty#8]
Hi, I'm assuming this is the right page for the Zatraty app on my phone... could you please do something about the bugs I described on the store comments? Especially the rounding down bug, as it makes the app basically useless. Thanks.

**Comment by ckazzku** [comment]
Ok

**Comment by ckazzku** [comment]
Done.
You can check v0.10.0 https://github.com/ckazzku/zatraty/releases/tag/v0.10.0
